language: python
sudo: false
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "tEAnydGtzCP5tzPkHpVUo0nzM8xjaAvNg/6ynHNyr6B78n33VX08xgVSzmih3bIz0ZqBDWi6v2tMNGMMO0LYtbjavvdCEfmzmOnFdPikZr8OJrWHiiup2edPzUArWPzsSX0lgzwmcOFV2t6IKcE0dDRvx6g3ETjs23iY4NIOtqXiNtKh19IqDlAX31S0ps8m9wPuCIm4HFbkwlJaQ4IKgBNSLMShfrZuBxSH8V6KNqfn+MDczmunfjiIDjwDYWvdxXgn+JqVbPEZTF40DzgQlSa3gOeTej2Ps+Fl9Yl5rfTqW4ndCaHtraWt7Yj3No5OWNjE/e3Nduw2RRCK+MhBGiEWDG3T0YtgDLkJ2PxnUKUq56Sh4fJm0VaFX6MNSptqrtzkqZnSFa7hQKh0fKaNK1nrJZ4vsrpLCV71LVHltwjfM77AvmSJuKMGip1DPJgF5hXm+cv2NlNmNKfNYvz6smBdr/CjpyutSZfzJhiBQimGvZigyY0xF/eNIRtVAV2UnXDTpAak4OcUbhzChakX1H6FHSdrBMBewEM8G9Hl5XctM6b9e7sbC44Tscwga1LfBsVl7pKryzqqrj+wHErZM7efuTr3CPTIk5Sh87K5wAB1HzoLA3k6sRAAymsvQLuHV867RL03QYRE10+JJbaS+3Nk1nKJh+ZptYKjcD8JVxk="
  on:
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
install:
  - pip install coverage==5.0.4
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)